name: Technical Debt
description: Report technical debt, refactoring needs, or code quality improvements
title: "[TECH DEBT] "
labels: ["technical-debt", "refactoring"]
body:
  - type: markdown
    attributes:
      value: |
        Use this template to document technical debt, code quality issues, or refactoring opportunities.

  - type: textarea
    id: debt-description
    attributes:
      label: Technical Debt Description
      description: Describe the technical debt or code quality issue
      placeholder: The current implementation of...
    validations:
      required: true

  - type: dropdown
    id: debt-category
    attributes:
      label: Category
      description: What type of technical debt is this?
      options:
        - Code Quality
        - Architecture
        - Performance
        - Security
        - Testing
        - Documentation
        - Dependencies
        - Build System
        - Developer Experience
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: How critical is this technical debt?
      options:
        - Critical - Blocking new development
        - High - Significant impact on maintainability
        - Medium - Moderate impact
        - Low - Minor improvement
    validations:
      required: true

  - type: textarea
    id: current-state
    attributes:
      label: Current State
      description: Describe the current implementation or state
      placeholder: |
        File: app/src/main/java/...
        Current approach: ...
    validations:
      required: true

  - type: textarea
    id: problems
    attributes:
      label: Problems Caused
      description: What problems does this technical debt cause?
      placeholder: |
        - Makes it difficult to...
        - Causes performance issues when...
        - Violates architectural principles by...
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed Solution
      description: How should this be addressed?
      placeholder: Refactor to use...
    validations:
      required: true

  - type: textarea
    id: migration-plan
    attributes:
      label: Migration/Refactoring Plan
      description: Outline the steps needed to address this technical debt
      placeholder: |
        1. Extract interface for...
        2. Create new implementation in...
        3. Migrate existing code to...
        4. Remove deprecated code
    validations:
      required: false

  - type: textarea
    id: architecture-alignment
    attributes:
      label: Architecture Alignment
      description: Reference docs/architecture.md - how does this align with our architecture?
      placeholder: This aligns with Section X.X of architecture.md...
    validations:
      required: false

  - type: dropdown
    id: effort-estimate
    attributes:
      label: Estimated Effort
      description: Rough estimate of effort required
      options:
        - Small (< 1 day)
        - Medium (1-3 days)
        - Large (3-5 days)
        - Extra Large (> 1 week)
    validations:
      required: true

  - type: checkboxes
    id: impact
    attributes:
      label: Impact Assessment
      description: What areas would be affected by addressing this debt?
      options:
        - label: Breaking changes to public APIs
        - label: Database migrations required
        - label: Dependency updates required
        - label: Documentation updates required
        - label: Test updates required
        - label: Build configuration changes

  - type: textarea
    id: risks
    attributes:
      label: Risks
      description: What risks are associated with addressing this technical debt?
      placeholder: |
        - Risk of introducing regressions in...
        - May temporarily impact performance during migration...
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any other relevant information
      placeholder: Related issues, PRs, or discussions...
    validations:
      required: false
