#!/bin/bash

# Development Environment Setup Script for iris_android
# This script sets up the development environment for the iris_android project

set -e

echo "=========================================="
echo "iris_android Development Environment Setup"
echo "=========================================="
echo ""

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Check if running from project root
if [ ! -f "settings.gradle.kts" ]; then
    echo -e "${RED}Error: This script must be run from the project root directory${NC}"
    exit 1
fi

echo "Step 1: Checking prerequisites..."
echo "-----------------------------------"

# Check for Android SDK
if [ -z "$ANDROID_HOME" ]; then
    echo -e "${RED}Error: ANDROID_HOME environment variable is not set${NC}"
    echo "Please set ANDROID_HOME to your Android SDK location"
    echo "Example: export ANDROID_HOME=/path/to/android/sdk"
    exit 1
else
    echo -e "${GREEN}✓${NC} ANDROID_HOME is set: $ANDROID_HOME"
fi

# Check for Android SDK installation
if [ ! -d "$ANDROID_HOME" ]; then
    echo -e "${RED}Error: Android SDK not found at $ANDROID_HOME${NC}"
    exit 1
else
    echo -e "${GREEN}✓${NC} Android SDK found"
fi

# Check for NDK
NDK_VERSION="26.1.10909125"
if [ ! -d "$ANDROID_HOME/ndk/$NDK_VERSION" ]; then
    echo -e "${YELLOW}Warning: NDK $NDK_VERSION not found${NC}"
    echo "Please install NDK $NDK_VERSION through Android Studio:"
    echo "  Settings → Android SDK → SDK Tools → NDK"
    echo ""
    read -p "Continue anyway? (y/n) " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        exit 1
    fi
else
    echo -e "${GREEN}✓${NC} NDK $NDK_VERSION found"
fi

# Check for Java
if command -v java &> /dev/null; then
    JAVA_VERSION=$(java -version 2>&1 | awk -F '"' '/version/ {print $2}' | cut -d'.' -f1)
    if [ "$JAVA_VERSION" -ge 17 ]; then
        echo -e "${GREEN}✓${NC} Java $JAVA_VERSION found"
    else
        echo -e "${YELLOW}Warning: Java 17+ recommended, found Java $JAVA_VERSION${NC}"
    fi
else
    echo -e "${RED}Error: Java not found${NC}"
    exit 1
fi

# Check for Git
if command -v git &> /dev/null; then
    echo -e "${GREEN}✓${NC} Git found"
else
    echo -e "${RED}Error: Git not found${NC}"
    exit 1
fi

echo ""
echo "Step 2: Setting up Git configuration..."
echo "-----------------------------------"

# Initialize submodules
if [ -f ".gitmodules" ]; then
    echo "Initializing Git submodules..."
    git submodule update --init --recursive
    echo -e "${GREEN}✓${NC} Submodules initialized"
else
    echo "No submodules found"
fi

# Install Git hooks
echo "Installing Git hooks..."
if [ ! -d ".git/hooks" ]; then
    mkdir -p .git/hooks
fi

# Use pre-commit hook from scripts directory
if [ -f "scripts/pre-commit" ]; then
    cp scripts/pre-commit .git/hooks/pre-commit
    chmod +x .git/hooks/pre-commit
    echo -e "${GREEN}✓${NC} Git hooks installed from scripts/pre-commit"
else
    # Fallback to creating inline hook
    cat > .git/hooks/pre-commit << 'EOF'
#!/bin/bash
# Pre-commit hook for iris_android

echo "Running pre-commit checks..."

# Run ktlint check
echo "Checking Kotlin code style..."
./gradlew ktlintCheck --daemon

if [ $? -ne 0 ]; then
    echo "❌ Ktlint check failed. Run './gradlew ktlintFormat' to fix formatting issues."
    exit 1
fi

# Run detekt
echo "Running static analysis..."
./gradlew detekt --daemon

if [ $? -ne 0 ]; then
    echo "❌ Detekt check failed. Please fix the reported issues."
    exit 1
fi

echo "✓ Pre-commit checks passed"
EOF
    chmod +x .git/hooks/pre-commit
    echo -e "${GREEN}✓${NC} Git hooks installed (fallback)"
fi

echo ""
echo "Step 3: Setting up local configuration..."
echo "-----------------------------------"

# Create local.properties if it doesn't exist
if [ ! -f "local.properties" ]; then
    echo "Creating local.properties..."
    cat > local.properties << EOF
# Automatically generated by setup-dev.sh
sdk.dir=$ANDROID_HOME
ndk.dir=$ANDROID_HOME/ndk/$NDK_VERSION

# Signing configuration (optional - for release builds)
# Uncomment and set these values if you have a signing key
#RELEASE_STORE_FILE=/path/to/keystore.jks
#RELEASE_STORE_PASSWORD=your_store_password
#RELEASE_KEY_ALIAS=your_key_alias
#RELEASE_KEY_PASSWORD=your_key_password
EOF
    echo -e "${GREEN}✓${NC} local.properties created"
else
    echo "local.properties already exists, skipping..."
fi

echo ""
echo "Step 4: Configuring Gradle..."
echo "-----------------------------------"

# Create gradle.properties if needed
if [ ! -f "gradle.properties" ]; then
    echo "Creating gradle.properties..."
    cat > gradle.properties << EOF
# Project-wide Gradle settings
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true
android.useAndroidX=true
kotlin.code.style=official
EOF
    echo -e "${GREEN}✓${NC} gradle.properties created"
else
    echo "gradle.properties already exists"
fi

echo ""
echo "Step 5: Building the project..."
echo "-----------------------------------"

echo "Running initial build (this may take a few minutes)..."
./gradlew assembleDebug --no-daemon

if [ $? -eq 0 ]; then
    echo -e "${GREEN}✓${NC} Build successful"
else
    echo -e "${RED}❌ Build failed${NC}"
    echo "Please check the error messages above and resolve any issues."
    exit 1
fi

echo ""
echo "Step 6: Running tests..."
echo "-----------------------------------"

echo "Running unit tests..."
./gradlew test --no-daemon

if [ $? -eq 0 ]; then
    echo -e "${GREEN}✓${NC} Tests passed"
else
    echo -e "${YELLOW}Warning: Some tests failed${NC}"
    echo "This may be expected for a fresh setup. Review the test results."
fi

echo ""
echo "=========================================="
echo "✓ Development environment setup complete!"
echo "=========================================="
echo ""
echo "Next steps:"
echo "1. Open the project in Android Studio"
echo "2. Sync Gradle files"
echo "3. Run the app on an emulator or device"
echo ""
echo "Useful commands:"
echo "  ./gradlew assembleDebug        - Build debug APK"
echo "  ./gradlew test                  - Run unit tests"
echo "  ./gradlew ktlintCheck          - Check code style"
echo "  ./gradlew ktlintFormat         - Format code"
echo "  ./gradlew detekt               - Run static analysis"
echo ""
echo "Documentation:"
echo "  CONTRIBUTING.md         - Contributing guidelines"
echo "  docs/architecture.md    - Architecture documentation"
echo "  SECURITY.md            - Security policy"
echo ""
echo "Happy coding! 🚀"
